% created by Jakob Nikolas Kather 2015 - 2016
% license: see separate LICENSE file, includes disclaimer

function featureVector = histogramJoint(imgInGray)
    % histogram-based features: central moment 1 to 5
    % input: grayscale image, values 0...1 (double precision floats)
    % compute histogram descriptors
    featureVector = [ mean(imgInGray(:)),...
                      var(imgInGray(:)),...
                      skewness(imgInGray(:)),...
                      kurtosis(imgInGray(:)),...
                      moment(imgInGray(:),5),...
                      moment(imgInGray(:),6),...
                      moment(imgInGray(:),7),...
                      moment(imgInGray(:),8),...
                      moment(imgInGray(:),9),...
                      moment(imgInGray(:),10),...
                      moment(imgInGray(:),11)];
end